# Generated by Django 3.2.11 on 2022-01-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=10, unique=True)),
                ('price', models.PositiveIntegerField(help_text='Product price in cents')),
                ('start_date', models.DateTimeField(help_text='Product available start date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
