# Generated by Django 3.2.11 on 2022-01-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(help_text='Product start date'),
        ),
    ]
